config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/new'
  root to: 'products#index'
  resources :products
  resources :sellers
  resources :buyers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
# frozen_string_literal: true

class Buyer < ApplicationRecord
  has_many :products
  has_many :sellers, through: :products
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :buyer
  belongs_to :seller
end

app/models/seller.rb
# frozen_string_literal: true

class Seller < ApplicationRecord
  has_many :buyers, through: :products
  has_many :products
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :remember
  validates :name, presence: true, allow_blank: false
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :posts

  private

  def remember
    token = SecureRandom.urlsafe_base64.to_s
    self.remember_token = Digest::SHA1.hexdigest token
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/buyers_controller.rb
# frozen_string_literal: true

class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[show edit update destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show; end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit; end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_buyer
    @buyer = Buyer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def buyer_params
    params.require(:buyer).permit(:name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :buyer_id)
  end
end

app/controllers/sellers_controller.rb
# frozen_string_literal: true

class SellersController < ApplicationController
  before_action :set_seller, only: %i[show edit update destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show; end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit; end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_seller
    @seller = Seller.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def seller_params
    params.require(:seller).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/buyers_helper.rb
# frozen_string_literal: true

module BuyersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/sellers_helper.rb
# frozen_string_literal: true

module SellersHelper
end

app/views/buyers/_form.html.erb
<%= form_with(model: buyer, local: true) do |form| %>
  <% if buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
        <% buyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buyers</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form', buyer: @buyer %>

<%= link_to 'Back', buyers_path %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @buyer.name %>
</p>


  <strong>Items Bought</strong>
<ul class="list-group">  
  <% @buyer.products.each do |product|%>
  <li class="list-group-item">
   <%= product.name %> | <%= product.seller.name%>
  </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Members Only</a>
</nav>

app/views/layouts/_nav.html.erb
  <nav class="site-header sticky-top py-1">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="#" aria-label="Product">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </a>
    <a class="py-2 d-none d-md-inline-block" href="#">Users</a>
    <a class="py-2 d-none d-md-inline-block" href="/">Product</a>
    <a class="py-2 d-none d-md-inline-block" href="/buyers">Buyer</a>
    <a class="py-2 d-none d-md-inline-block" href="/sellers">Seller</a>
  </div>
  </nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Relation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
   <%= render 'layouts/nav' %> 
    <%= yield %>
  <%# <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :buyer_id %>
    <%= form.text_field :buyer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Buyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.buyer.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @product.buyer.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sellers/_form.html.erb
<%= form_with(model: seller, local: true) do |form| %>
  <% if seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
        <% seller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope = "col">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New Seller</h1>

<%= render 'form', seller: @seller %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>

  <strong>Items Sold</strong>
<ul class="list-group">  
  <% @seller.products.each do |product|%>
  <li class="list-group-item">
   <%= product.name %> | <%= product.buyer.name%>
  </li>
  <% end %>
</ul>
 

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>